### ISSUE TITLE
Using this plugin seems to break the site title home button

### ISSUE THREAD

**Issue by aarongray** [angusmcleod/discourse-header-search#1]
Howdy!

Was taking this plugin for a spin today, and I'm seeing what appears to be a bug. My site title (in the header just to the left of the new search box) no longer takes users to the home screen on click. Not sure if it makes a difference, but I'm using a text title rather than a logo.

**Comment by angusmcleod** [comment]
@aarongray Hey, thanks for reporting this. Should be fixed now:

https://github.com/angusmcleod/discourse-header-search/commit/d5a37a0cb91d0218b4ea37f7e61e34f9f2d72d18

**Comment by aarongray** [comment]
Nice! 👍
