### ISSUE TITLE
Could not find module `discourse-common/helpers/fa-icon`

### ISSUE THREAD

**Issue by ghost** [angusmcleod/discourse-header-search#2]
My Discourse is on stable branch, and using your library. Thank you for what you have done so far. 

I see this commit https://github.com/angusmcleod/discourse-header-search/commit/de4993c18e2fcbbf341e973365ac0d96d2146b8a

But what are you done that for?

When I use this, I got a white screen with an error in my console: 

> caught Error: Could not find module `discourse-common/helpers/fa-icon` imported from `discourse/plugins/discourse-header-search/discourse/widgets/header-search-results

**Comment by angusmcleod** [comment]
@helperhaps Hey, this was required due to an update in Discourse core. Please updated your Discourse instance and this plugin will work as normal.

**Comment by ghost** [comment]
@angusmcleod  But I am using the stable branch, the newest one. In other word, when I bootstrap a discourse with stable branch, the browser will be a blank page and error uncaught above. 

So to make discourse work, i have to uninstall this plugin.

**Comment by angusmcleod** [comment]
@helperhaps The 'stable' version uses a different folder structure. This plugin supports the latest commit on 'master', which is the default option for upgrade in /admin/upgrade. Unfortunately, I can't support both at once.
